# Generated by Django 5.2.12 on 2026-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_ed25519_public_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_x25519_public_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
